### ISSUE TITLE
由于安全原因，此微信号不能使用网页版微信

### ISSUE THREAD

**Issue by ai-sauce** [SXS-PRIVATE/AutoWeChat#2]
按照你说的先登录网页版的文件传输助手之后还是不能登录网页版微信。
由于安全原因，此微信号不能使用网页版微信。你可以前往微信官网 https://weixin.qq.com/ 下载客户端登录。

**Comment by youonly-once** [comment]
现在又不行了，刚开始可以

**Comment by ai-sauce** [comment]
好吧

**Comment by youonly-once** [comment]
添加UOS Header，已解决“为了保障你的账号安全，暂不支持使用网页版微信”问题
