### ISSUE TITLE
maven 报错jfree找不到

### ISSUE THREAD

**Issue by big-tooth** [SXS-PRIVATE/AutoWeChat#3]
Cannot resolve org.jfree:com.springsource.org.jfree:1.0.12

**Comment by youonly-once** [comment]
Maven仓库  
<mirrors>
    

       <mirror>
            <id>nexus-aliyun</id>
            <mirrorOf>*,!jeecg,!jeecg-snapshots</mirrorOf>
            <name>Nexus aliyun</name>
            <url>http://maven.aliyun.com/nexus/content/groups/public</url>
        </mirror> 

  </mirrors>
